2025-08-20 17:33:58,841 -  nornir.core -     INFO -        run() - Running task 'check_interfaces' with args {} on 2 hosts
2025-08-20 17:37:07,804 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ip int brief', 'enable': True} on 2 hosts
2025-08-20 17:37:12,257 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show version', 'enable': True} on 2 hosts
2025-08-20 17:37:13,060 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'enable': True} on 2 hosts
2025-08-20 17:37:23,212 -  nornir.core -     INFO -        run() - Running task 'push_config' with args {} on 2 hosts
2025-08-20 17:37:44,193 -  nornir.core -     INFO -        run() - Running task 'push_config' with args {} on 2 hosts
2025-08-20 17:51:36,351 -  nornir.core -     INFO -        run() - Running task 'push_config' with args {} on 2 hosts
2025-08-20 17:57:29,184 -  nornir.core -     INFO -        run() - Running task 'push_config' with args {} on 2 hosts
2025-08-20 17:58:45,348 -  nornir.core -     INFO -        run() - Running task 'push_config' with args {} on 2 hosts
2025-08-20 18:02:27,379 -  nornir.core -     INFO -        run() - Running task 'push_config' with args {} on 2 hosts
2025-08-20 19:48:27,576 -  nornir.core -     INFO -        run() - Running task 'push_config' with args {} on 2 hosts
2025-08-20 19:51:18,979 -  nornir.core -     INFO -        run() - Running task 'push_config' with args {} on 2 hosts
2025-08-20 19:51:47,924 -  nornir.core -     INFO -        run() - Running task 'push_config' with args {} on 2 hosts
2025-08-20 20:03:40,366 -  nornir.core -     INFO -        run() - Running task 'backup_config' with args {} on 2 hosts
2025-08-20 20:03:44,329 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/venv/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/venv/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 42, in netmiko_send_config
    raise ValueError("Must specify either config_commands or config_file")
ValueError: Must specify either config_commands or config_file

2025-08-20 20:03:44,329 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/venv/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/venv/lib/python3.9/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 42, in netmiko_send_config
    raise ValueError("Must specify either config_commands or config_file")
ValueError: Must specify either config_commands or config_file

2025-08-20 20:03:44,330 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'backup_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/venv/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/Nornir_Framework/extra_exercises/backup_configs.py", line 12, in backup_config
    task.run(task=netmiko_send_config, command_string="terminal length 0", enable=True)
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/venv/lib/python3.9/site-packages/nornir/core/task.py", line 173, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netmiko_send_config (failed)


2025-08-20 20:03:44,330 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'backup_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/venv/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/Nornir_Framework/extra_exercises/backup_configs.py", line 12, in backup_config
    task.run(task=netmiko_send_config, command_string="terminal length 0", enable=True)
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/venv/lib/python3.9/site-packages/nornir/core/task.py", line 173, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netmiko_send_config (failed)


2025-08-20 20:06:35,693 -  nornir.core -     INFO -        run() - Running task 'backup_config' with args {} on 2 hosts
2025-08-20 20:06:35,694 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'backup_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/venv/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/Nornir_Framework/extra_exercises/backup_configs.py", line 13, in backup_config
    task.run(task=netmiko_send_commands, command_string="terminal length 0", enable=True)
NameError: name 'netmiko_send_commands' is not defined

2025-08-20 20:06:35,694 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'backup_config' failed with traceback:
Traceback (most recent call last):
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/venv/lib/python3.9/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/hugothomazpinheirodesouza/python-envs/book-mastering-python-networking/chapter-2/Nornir_Framework/extra_exercises/backup_configs.py", line 13, in backup_config
    task.run(task=netmiko_send_commands, command_string="terminal length 0", enable=True)
NameError: name 'netmiko_send_commands' is not defined

2025-08-20 20:07:01,001 -  nornir.core -     INFO -        run() - Running task 'backup_config' with args {} on 2 hosts
2025-08-20 20:08:08,716 -  nornir.core -     INFO -        run() - Running task 'backup_config' with args {} on 2 hosts
